version: "2"

run:
  timeout: 5m

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - (*github.com/fatih/color.Color).Fprint
        - (*github.com/fatih/color.Color).Fprintf
        - (*github.com/fatih/color.Color).Fprintln
        - (*github.com/fatih/color.Color).Print
        - (*github.com/fatih/color.Color).Printf
        - (*github.com/fatih/color.Color).Println
